//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongsAbout.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class User : global::System.Configuration.ApplicationSettingsBase {
        
        private static User defaultInstance = ((User)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new User())));
        
        public static User Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SpotifyAPI.Web.Models.Image ProfilePic {
            get {
                return ((global::SpotifyAPI.Web.Models.Image)(this["ProfilePic"]));
            }
            set {
                this["ProfilePic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SpotifyAPI.Web.Models.FollowedArtists FollowedArtists {
            get {
                return ((global::SpotifyAPI.Web.Models.FollowedArtists)(this["FollowedArtists"]));
            }
            set {
                this["FollowedArtists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SpotifyAPI.Web.Models.FeaturedPlaylists FeaturedPlaylists {
            get {
                return ((global::SpotifyAPI.Web.Models.FeaturedPlaylists)(this["FeaturedPlaylists"]));
            }
            set {
                this["FeaturedPlaylists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SpotifyAPI.Web.SpotifyWebAPI SpotifyWebAPI {
            get {
                return ((global::SpotifyAPI.Web.SpotifyWebAPI)(this["SpotifyWebAPI"]));
            }
            set {
                this["SpotifyWebAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SpotifyAPI.Web.Models.PublicProfile PublicProfile {
            get {
                return ((global::SpotifyAPI.Web.Models.PublicProfile)(this["PublicProfile"]));
            }
            set {
                this["PublicProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HotTrack")]
        public global::System.Drawing.Color BackColor {
            get {
                return ((global::System.Drawing.Color)(this["BackColor"]));
            }
            set {
                this["BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Highlight")]
        public global::System.Drawing.Color Highlight {
            get {
                return ((global::System.Drawing.Color)(this["Highlight"]));
            }
            set {
                this["Highlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TextColor {
            get {
                return ((global::System.Drawing.Color)(this["TextColor"]));
            }
            set {
                this["TextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial Unicode MS, 7.8pt")]
        public global::System.Drawing.Font ParagraphFont {
            get {
                return ((global::System.Drawing.Font)(this["ParagraphFont"]));
            }
            set {
                this["ParagraphFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial Unicode MS, 10.2pt")]
        public global::System.Drawing.Font HeaderFont {
            get {
                return ((global::System.Drawing.Font)(this["HeaderFont"]));
            }
            set {
                this["HeaderFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public object LocalProfilePic {
            get {
                return ((object)(this["LocalProfilePic"]));
            }
            set {
                this["LocalProfilePic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SpotifyAPI.Web.Models.PrivateProfile PrivateProfile {
            get {
                return ((global::SpotifyAPI.Web.Models.PrivateProfile)(this["PrivateProfile"]));
            }
            set {
                this["PrivateProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrivateId {
            get {
                return ((string)(this["PrivateId"]));
            }
            set {
                this["PrivateId"] = value;
            }
        }
    }
}
