//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongsAbout_DesktopApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class User : global::System.Configuration.ApplicationSettingsBase {
        
        private static User defaultInstance = ((User)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new User())));
        
        public static User Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SpotifyAPI.Web.Models.PrivateProfile u_PRIVATE_PROFILE {
            get {
                return ((global::SpotifyAPI.Web.Models.PrivateProfile)(this["u_PRIVATE_PROFILE"]));
            }
            set {
                this["u_PRIVATE_PROFILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SpotifyAPI.Web.Models.Image u_PROFILE_PIC {
            get {
                return ((global::SpotifyAPI.Web.Models.Image)(this["u_PROFILE_PIC"]));
            }
            set {
                this["u_PROFILE_PIC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SpotifyAPI.Web.Models.FollowedArtists u_FOLLOWED_ARTISTS {
            get {
                return ((global::SpotifyAPI.Web.Models.FollowedArtists)(this["u_FOLLOWED_ARTISTS"]));
            }
            set {
                this["u_FOLLOWED_ARTISTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SpotifyAPI.Web.Models.FeaturedPlaylists u_FEATURED_PLAYLISTS {
            get {
                return ((global::SpotifyAPI.Web.Models.FeaturedPlaylists)(this["u_FEATURED_PLAYLISTS"]));
            }
            set {
                this["u_FEATURED_PLAYLISTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SpotifyAPI.Web.SpotifyWebAPI u_SPOTIFY_WEB_API {
            get {
                return ((global::SpotifyAPI.Web.SpotifyWebAPI)(this["u_SPOTIFY_WEB_API"]));
            }
            set {
                this["u_SPOTIFY_WEB_API"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SpotifyAPI.Web.Models.PublicProfile u_PUBLIC_PROFILE {
            get {
                return ((global::SpotifyAPI.Web.Models.PublicProfile)(this["u_PUBLIC_PROFILE"]));
            }
            set {
                this["u_PUBLIC_PROFILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string u_USER_ID {
            get {
                return ((string)(this["u_USER_ID"]));
            }
            set {
                this["u_USER_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
