<?xml version="1.0" encoding="utf-8"?><Database Name="SongsAboutSQLDB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JDEGRAW\SQLEXPRESS;Initial Catalog=SongsAboutSQLDB;Integrated Security=True" SettingsObjectName="SongsAbout_DesktopApp.Properties.Settings" SettingsPropertyName="SongsAboutSQLDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Artists" Member="Artists">
    <Type Name="Artist">
      <Column Name="ID" Storage="_artist_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="a_name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="a_bio" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="a_website" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="a_spotify_uri" AutoSync="Always" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="a_profile_pic" Type="System.Byte[]" DbType="Image" CanBeNull="true" />
      <Association Name="Artist_Album" Member="Albums" ThisKey="ID" OtherKey="artist_id" Type="Album" />
      <Association Name="Artist_TrackArtists" Member="TrackArtists" ThisKey="ID" OtherKey="artist_id" Type="TrackArtists" />
    </Type>
  </Table>
  <Table Name="dbo.Genres" Member="Genres">
    <Type Name="Genre">
      <Column Name="genre" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Genre_TrackGenre" Member="TrackGenres" ThisKey="genre" OtherKey="tg_genre" Type="TrackGenre" />
      <Association Name="Genre_AlbumGenre" Member="AlbumGenres" ThisKey="genre" OtherKey="genre" Type="AlbumGenre" />
    </Type>
  </Table>
  <Table Name="dbo.TrackGenres" Member="TrackGenres">
    <Type Name="TrackGenre">
      <Column Name="ID" Storage="_tg_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="track_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="genre" Member="tg_genre" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Genre_TrackGenre" Member="Genre1" ThisKey="tg_genre" OtherKey="genre" Type="Genre" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Track_TrackGenre" Member="Track" ThisKey="track_id" OtherKey="ID" Type="Track" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Albums" Member="Albums">
    <Type Name="Album">
      <Column Name="ID" Storage="_album_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="artist_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="al_title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="al_year" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="al_spotify_uri" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="al_cover_art" Type="System.Byte[]" DbType="Image" CanBeNull="true" />
      <Association Name="Album_AlbumGenre" Member="AlbumGenres" ThisKey="ID" OtherKey="album_id" Type="AlbumGenre" />
      <Association Name="Album_AlbumTracks" Member="AlbumTracks" ThisKey="ID" OtherKey="album_id" Type="AlbumTracks" />
      <Association Name="Artist_Album" Member="Artist" ThisKey="artist_id" OtherKey="ID" Type="Artist" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tracks" Member="Tracks">
    <Type Name="Track">
      <Column Name="ID" Storage="_track_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="track_name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="track_spotify_uri" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="track_length_minutes" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="track_artist_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="can_play" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="list_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Track_TrackGenre" Member="TrackGenres" ThisKey="ID" OtherKey="track_id" Type="TrackGenre" />
      <Association Name="Track_TrackTag" Member="TrackTags" ThisKey="ID" OtherKey="track_id" Type="TrackTag" />
      <Association Name="Track_AlbumTracks" Member="AlbumTracks" ThisKey="ID" OtherKey="track_id" Type="AlbumTracks" />
      <Association Name="Track_TrackArtists" Member="TrackArtists" ThisKey="ID" OtherKey="track_id" Type="TrackArtists" />
    </Type>
  </Table>
  <Table Name="dbo.Tags" Member="Tags">
    <Type Name="Tag">
      <Column Name="tag_text" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Tag_TrackTag" Member="TrackTags" ThisKey="tag_text" OtherKey="tag_text" Type="TrackTag" />
    </Type>
  </Table>
  <Table Name="dbo.TrackTags" Member="TrackTags">
    <Type Name="TrackTag">
      <Column Name="ID" Storage="_track_tag_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tag_text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="track_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tag_TrackTag" Member="Tag" ThisKey="tag_text" OtherKey="tag_text" Type="Tag" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Track_TrackTag" Member="Track" ThisKey="track_id" OtherKey="ID" Type="Track" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AlbumGenres" Member="AlbumGenres">
    <Type Name="AlbumGenre">
      <Column Name="ID" Storage="_al_g_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="album_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="genre" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Album_AlbumGenre" Member="Album" ThisKey="album_id" OtherKey="ID" Type="Album" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Genre_AlbumGenre" Member="Genre1" ThisKey="genre" OtherKey="genre" Type="Genre" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.AlbumTracks" Member="AlbumTracks">
    <Type Name="AlbumTracks">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="album_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="track_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Album_AlbumTracks" Member="Album" ThisKey="album_id" OtherKey="ID" Type="Album" IsForeignKey="true" />
      <Association Name="Track_AlbumTracks" Member="Track" ThisKey="track_id" OtherKey="ID" Type="Track" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrackArtists" Member="TrackArtists">
    <Type Name="TrackArtists">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="artist_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="track_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Artist_TrackArtists" Member="Artist" ThisKey="artist_id" OtherKey="ID" Type="Artist" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Track_TrackArtists" Member="Track" ThisKey="track_id" OtherKey="ID" Type="Track" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>