//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongsAbout.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Track
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Track()
        {
            this.privateTags = new HashSet<Tag>();
            this.privatePlaylists = new HashSet<Playlist>();
            this.privateArtists = new HashSet<Artist>();
            this.privateGenres = new HashSet<Genre>();
            this.privateTopics = new HashSet<Topic>();

        }

        public int ID { get; set; }
        private string name { get; set; }
        private string track_spotify_uri { get; set; }
        private Nullable<double> track_length_minutes { get; set; }
        private int track_artist_id { get; set; }
        private string can_play { get; set; }
        private int track_album_id { get; set; }
        public bool CanPlay
        {
            get
            {
                if (can_play == "1")
                    return true;
                else
                    return false;
            }
            set
            {
                if (value)
                    this.can_play = "1";
                else
                    this.can_play = "0";

            }
        }
        public string CanPlayString
        {
            get { return this.can_play; }
        }
        private Album privateAlbum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<Tag> privateTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<Playlist> privatePlaylists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<Artist> privateArtists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<Genre> privateGenres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<Topic> privateTopics { get; set; }
    }
}
